version: '3.8'
services:
    web:
        build: .
        ports:
            - '3000:3000'
        env_file:
            - .env.local
        volumes:
            - .:/app
            - /app/node_modules
        stdin_open: true
        tty: true
